Upgrade pytest from 6.2.2 to 7.4.3
Without this, I get a `TypeError: required field "lineno" missing from alias` error with Python 3.10. E.g.:

```
$ tox -e py310
.pkg: _optional_hooks> python /Users/abramowi/Code/OpenSource/detect-secrets/.venv/lib/python3.10/site-packages/pyproject_api/_backend.py True
attrs==21.4.0
 setuptools.build_meta __legacy__
.pkg: get_requires_for_build_sdist> python /Users/abramowi/Code/OpenSource/detect-secrets/.venv/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_wheel> python /Users/abramowi/Code/OpenSource/detect-secrets/.venv/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: prepare_metadata_for_build_wheel> python /Users/abramowi/Code/OpenSource/detect-secrets/.venv/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: build_sdist> python /Users/abramowi/Code/OpenSource/detect-secrets/.venv/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
py310: install_package> python -I -m pip install --force-reinstall --no-deps /Users/abramowi/Code/OpenSource/detect-secrets/.tox/.tmp/package/4/detect_secrets-1.4.0.tar.gz
py310: commands[0]> coverage erase
py310: commands[1]> coverage run -m pytest --strict tests
ImportError while loading conftest '/Users/abramowi/Code/OpenSource/detect-secrets/tests/conftest.py'.
TypeError: required field "lineno" missing from alias
py310: exit 4 (0.16 seconds) /Users/abramowi/Code/OpenSource/detect-secrets> coverage run -m pytest --strict tests pid=74616
.pkg: _exit> python /Users/abramowi/Code/OpenSource/detect-secrets/.venv/lib/python3.10/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
  py310: FAIL code 4 (1.43=setup[1.21]+cmd[0.06,0.16] seconds)
  evaluation failed :( (1.56 seconds)
```